Eddy changes.

diff --git a/bin/DWISaveBZero b/bin/DWISaveBZero
--- a/bin/DWISaveBZero
+++ b/bin/DWISaveBZero
@@ -6,16 +6,29 @@
 
 if [ -z "$1" ]
 then
-	echo "Usage: $0 <subject id>"
+	echo "Usage: $0 <subject id> [--use-eddy]"
 else
 		
 # do the B0 image
 	mkdir -p $DWIBZERO
 	
-	if [ "x`imglob $DWIREORIENT/${1}`" = "x" ]
+	if [ "$2" == "--use-eddy" ]
 	then
-		echo "DWI Reorient image $DWIREORIENT/${1} not found, run --dwi-reorient"
-		exit 1
+		
+		if [ "x`imglob $DWIEDDY/${1}.eddy_outlier_free_data.nii*`" = "x" ]
+		then
+			echo "DWI Reorient image $DWIEDDY/${1}.eddy_outlier_free_data not found, run topup and eddy"
+			exit 1
+		fi
+		fslroi $DWIEDDY/${1}.eddy_outlier_free_data $DWIBZERO/${1} 0 1
+	
+	else
+
+		if [ "x`imglob $DWIREORIENT/${1}`" = "x" ]
+		then
+			echo "DWI Reorient image $DWIREORIENT/${1} not found, run --dwi-reorient"
+			exit 1
+		fi
+		fslroi $DWIREORIENT/${1} $DWIBZERO/${1} 0 1
 	fi
-	fslroi $DWIREORIENT/${1} $DWIBZERO/${1} 0 1
 fi
